const sampleListings = [
    {
        title: "Cozy Beachfront Cottage",
        description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 1500,
        location: "Malibu",
        country: "United States",
    },
    {
        title: "Modern Loft in Downtown",
        description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
        image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 1200,
        location: "New York City",
        country: "United States",
    },
    {
        title: "Mountain Retreat",
        description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
        image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 1000,
        location: "Aspen",
        country: "United States",
    },
    {
        title: "Historic Villa in Tuscany",
        description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 2500,
        location: "Florence",
        country: "Italy",
    },
    {
        title: "Secluded Treehouse Getaway",
        description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
        image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 800,
        location: "Portland",
        country: "United States",
    },
    {
        title: "Beachfront Paradise",
        description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
        image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 2000,
        location: "Cancun",
        country: "Mexico",
    },
    {
        title: "Rustic Cabin by the Lake",
        description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
        image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 900,
        location: "Lake Tahoe",
        country: "United States",
    },
    {
        title: "Luxury Penthouse with City Views",
        description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
        image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
        price: 3500,
        location: "Los Angeles",
        country: "United States",
    },
    {
        title: "Ski-In/Ski-Out Chalet",
        description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
        image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 3000,
        location: "Verbier",
        country: "Switzerland",
    },
    {
        title: "Safari Lodge in the Serengeti",
        description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
        image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 4000,
        location: "Serengeti National Park",
        country: "Tanzania",
    },
    {
        title: "Elegant Apartment in Paris",
        description: "Stay in the City of Light with this charming Parisian apartment. Perfect for romantic getaways.",
        image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8cGFyaXN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
        price: 2200,
        location: "Paris",
        country: "France",
    },
    {
        title: "Desert Oasis Villa",
        description: "Relax in this luxurious villa located in the heart of the desert. A truly unique experience.",
        image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dmFjYXRpb24lMjBsb2JieXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 5000,
        location: "Dubai",
        country: "United Arab Emirates",
    },
    {
        title: "Island Bungalow",
        description: "Enjoy crystal-clear waters and white sandy beaches with this serene island bungalow.",
        image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YmFuZ2Fsb3d8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
        price: 3500,
        location: "Maldives",
        country: "Maldives",
    },
    {
        title: "Japanese Ryokan",
        description: "Immerse yourself in Japanese culture with a stay at this traditional ryokan. Hot springs included!",
        image: "https://images.unsplash.com/photo-1561406633-8a44d636fc24?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGp1bWV8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
        price: 1800,
        location: "Kyoto",
        country: "Japan",
    },
    {
        title: "Charming Countryside Farmhouse",
        description: "Revel in the tranquility of the countryside with this rustic farmhouse. A perfect retreat for families.",
        image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8ZmFybWhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 1200,
        location: "Sussex",
        country: "United Kingdom",
    },
    {
        title: "Ice Hotel Adventure",
        description: "Stay cool at this one-of-a-kind ice hotel. A unique experience you won't forget!",
        image: "https://images.unsplash.com/photo-1519657806813-97e61fbd7b9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aWNlJTIwaG90ZWx8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
        price: 2700,
        location: "Jukkasjärvi",
        country: "Sweden",
    },
    {
        title: "Safari Tent",
        description: "Get close to nature while still enjoying comfort in this upscale safari tent.",
        image: "https://images.unsplash.com/photo-1560347875-aef76df4c98b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c2FmYXJpJTIwdGVudHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 1400,
        location: "Maasai Mara",
        country: "Kenya",
    },
    {
        title: "Overwater Bungalow",
        description: "Wake up to stunning ocean views in this luxurious overwater bungalow.",
        image: "https://images.unsplash.com/photo-1565291960260-8a94419b6d85?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGJ1bmdhbG93fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 6000,
        location: "Bora Bora",
        country: "French Polynesia",
    },
    {
        title: "Luxury Yacht Stay",
        description: "Sail into luxury with this exclusive yacht stay. Perfect for those who love the sea.",
        image: "https://images.unsplash.com/photo-1543486738-dc7aa5a24dcf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8eWFjaHR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
        price: 8000,
        location: "Monte Carlo",
        country: "Monaco",
    },
    
    {
        title: "Treehouse Adventure",
        description: "Reconnect with your childhood dreams in this adventurous treehouse experience.",
        image: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8dHJlZWhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 950,
        location: "Sequoia National Park",
        country: "United States",
    },
    {
        title: "Modern Urban Loft",
        description: "Experience the vibrant city life in this stylish and modern loft, perfect for urban explorers.",
        image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bG9mdHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 3000,
        location: "New York City",
        country: "United States",
    },
    {
        title: "Beachside Cottage",
        description: "Relax by the sea with this charming beachside cottage offering breathtaking ocean views.",
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YmVhY2glMjBjb3R0YWdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 1500,
        location: "Santa Monica",
        country: "United States",
    },
    {
        title: "Chalet in the Alps",
        description: "Enjoy the stunning Alpine views and world-class skiing from this cozy mountain chalet.",
        image: "https://images.unsplash.com/photo-1535914254981-b5012eebbd15?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2hhbGV0JTIwYWxwc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 4500,
        location: "Zermatt",
        country: "Switzerland",
    },
    {
        title: "Rustic Cabin in the Woods",
        description: "Escape to nature in this cozy cabin surrounded by serene forests and wildlife.",
        image: "https://images.unsplash.com/photo-1479857147596-6c295f8d1a9a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FiaW4lMjB3b29kc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 1200,
        location: "Banff",
        country: "Canada",
    },
    {
        title: "Mediterranean Villa",
        description: "Bask in the sun with this luxurious villa overlooking the stunning Mediterranean coastline.",
        image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWVkaXRlcnJhbmVhbiUyMHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 7000,
        location: "Santorini",
        country: "Greece",
    },
    {
        title: "Luxury Penthouse",
        description: "Stay in the lap of luxury with this stunning penthouse featuring panoramic city views.",
        image: "https://images.unsplash.com/photo-1499952127939-9bb6fa42c4d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGVudGhvdXNlJTIwbHV4dXJ5fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
        price: 9000,
        location: "Dubai",
        country: "United Arab Emirates",
    },
    {
        title: "Historic Castle",
        description: "Live like royalty in this beautifully preserved castle with rich history and charm.",
        image: "https://images.unsplash.com/photo-1533729080763-8c3d18d6c4a6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y2FzdGxlJTIwaGlzdG9yeXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 12000,
        location: "Edinburgh",
        country: "Scotland",
    },
    {
        title: "Eco-Friendly Dome",
        description: "Experience sustainable living with this unique dome home designed with eco-conscious travelers in mind.",
        image: "https://images.unsplash.com/photo-1501680301477-24420506d876?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9tZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 1800,
        location: "Bali",
        country: "Indonesia",
    },
    {
        title: "Countryside Vineyard Estate",
        description: "Savor fine wine and tranquility with this estate surrounded by lush vineyards.",
        image: "https://images.unsplash.com/photo-1571426442886-fb760c5cfded?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmluZXlhcmR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
        price: 5500,
        location: "Tuscany",
        country: "Italy",
    },
    {
        title: "Floating House",
        description: "Stay afloat in this innovative and serene floating house on a beautiful lake.",
        image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZmxvYXRpbmclMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 4000,
        location: "Amsterdam",
        country: "Netherlands",
    }
];

module.exports = {data : sampleListings};